worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /tmp/nginx_access.log;
    error_log /tmp/nginx_error.log;

    server {
        listen 3001;

        location / {
            proxy_pass http://0.0.0.0:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Ingress-Path $http_x_ingress_path;
        }
    }
}
