worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8099;

        location / {
            proxy_pass http://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Ingress-Path $http_x_ingress_path;
        }
    }
}
